### ISSUE TITLE
Change 'Integration' naming to 'Contract'

### ISSUE THREAD

**Issue by melihbirim** [tubuarge/tubuio-sdk-go#2]
https://github.com/tubuarge/tubuio-sdk-go/blob/c40bf55acfd654f67b82033ea413ac950f4443a4/api/api.go#L33

**Comment by hemreari** [comment]
Fixed in https://github.com/tubuarge/tubuio-sdk-go/commit/ad2130d8c2ef09b49bb334cdc745967e2d261c89.
